name: Scheduled Python Script

on:
  schedule:
    - cron: '30 3 * * 2' # 每周二11时30分开始学习
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#providing-inputs
  workflow_dispatch:
    inputs:
      unconditional-invoking:
        description: '手动学习'
        type: boolean
        required: true
        default: true

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    
    - name: Run Python script
      run: python qndxx.py

    - name: Upload log file
      uses: actions/upload-artifact@v3
      with:
        name: log-files
        path: qndxx.log

